version: "3"
services:
  w-app-backend:
    image: w-app-backend
    container_name: w-app-backend
    build: .
    restart: "always"
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 3g

networks:
  mynetwork:
    driver: bridge
