import { StyleSheet, Dimensions } from "react-native";

const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  ImageContainer: {
    width: screenWidth,
    height: screenWidth * 0.15,
    backgroundPosition: "center center",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    display: "flex",
    borderBottomColor: "#232222",
    borderBottomWidth: 1,
  },
  headingBox: {
    display: "flex",
    width: screenWidth * 0.5,
    height: screenWidth * 0.15,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  Image: {
    resizeMode: "cover",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  backIcon_2: {
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: "#404040",
    zIndex: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: screenWidth * 0.15,
    left: screenWidth * 0.04,
  },
  backIconBox: {
    position: "absolute",
    top: screenWidth * 0.03,
    left: screenWidth * 0.02,
    backgroundColor: "transparent",
    zIndex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: 30,
    height: 30,
  },
  detailIcon: {
    position: "absolute",
    top: screenWidth * 0.03,
    right: screenWidth * 0.02,
    width: 35,
    height: 35,
    zIndex: 1,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  companyName: {
    color: "white",
    fontSize: 18,
    fontFamily: "Red Hat Display",
    fontWeight: "500",
    lineHeight: 23,
    textAlign: "left",
    marginLeft: 10,
    marginRight: 10,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "black",
    opacity: 0.5,
  },
  membersText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    fontFamily: "Poppins",
  },
  inputContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    width: screenWidth * 0.8,
    marginLeft: screenWidth * 0.03,
  },
  inputWrapper: {
    width: "100%",
    paddingHorizontal: 5,
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 20,
  },
  inputbox: {
    borderWidth: 0,
    width: "85%",
    fontSize: 17,
    padding: 9,
    flex: 1,
    marginLeft: 5,
    lineHeight: 20,
    color: "white",
    fontFamily: "Raleway",
  },
  senderDetails: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginLeft: -5,
    marginBottom: 5,
  },
  senderName: {
    color: "green",
    fontSize: 13,
    fontFamily: "Raleway",
    fontWeight: "bold",
    marginLeft: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: -15,
  },
  senderImage: {
    width: 35,
    height: 35,
    borderRadius: 100000,
    borderWidth: 2,
    borderColor: "white",
    marginLeft: 5,
  },
  imageGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    marginTop: -5,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "black",
    justifyContent: "center",
  },
  imageWrapper: {
    width: "100%",
    height: "82%",
    borderRadius: 30,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  fullImage: {
    width: screenWidth * 0.9,
    height: screenHeight * 0.8,
  },
  fullVideo: {
    width: screenWidth * 0.9,
    height: screenHeight * 0.7,
  },
  fullImageContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    width: screenWidth,
    height: screenHeight * 0.8,
    padding: 10,
    marginBottom: -30,
  },
  fullVideoContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    width: screenWidth,
    height: screenHeight * 0.7,
    padding: 10,
  },
  videoWrapper: {
    position: "relative",
    width: screenWidth * 0.9,
    height: screenHeight * 0.8,
  },
  playButtonContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -20 }, { translateY: -20 }],
    justifyContent: "center",
    alignItems: "center",
  },
  saveButtonContainer: {
    width: "70%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "white",
    backgroundColor: "black",
    alignSelf: "center",
    marginBottom: 60,
  },
  modalTwoContainer: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "transparent",
    width: "100%",
  },
  bottomSheet: {
    backgroundColor: "#151515",
    padding: 16,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: 250,
    width: "100%",
  },
  uploadCard: {
    width: 100,
    height: 100,
    backgroundColor: "#151515",
    borderRadius: 10,
    borderColor: "#6b6b6b",
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    marginTop: 20,
    marginRight: 20,
  },
  uploadButton: {
    width: 34,
    height: 34,
    backgroundColor: "#404040",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  UploadCardOuter: {
    width: 210,
    height: 100,
    borderRadius: 100,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  uploadText: {
    color: "white",
    fontSize: 18,
    fontFamily: "Red Hat Display",
    fontWeight: "250",
    marginTop: 13,
  },
  sendButton: {
    width: 30,
    height: 30,
    backgroundColor: "#0451f8",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  mediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    marginTop: -5,
  },
});
